name: ${name}
version: ${version}
main: ${group}.${name.toLowerCase()}.paper.${name}Plugin
description: This is a Paper plugin.
author: Loapu
website: https://docs.luminacollection.net/nameshift/
api-version: 1.19
dependencies:
  - name: Axios
    required: true
    bootstrap: false
  - name: SuperVanish
    required: false
    bootstrap: false
  - name: PremiumVanish
    required: false
    bootstrap: false
  - name: VelocityVanish
    required: false
    bootstrap: false
  - name: LuckPerms
    required: false
    bootstrap: false
load-after:
  - name: Axios
    bootstrap: false
  - name: SuperVanish
    bootstrap: false
  - name: PremiumVanish
    bootstrap: false
  - name: VelocityVanish
    bootstrap: false
  - name: LuckPerms
    bootstrap: false